### ISSUE TITLE
AWS elasticbeanstalk deployment

### ISSUE THREAD

**Issue by ssammut** [Phobetor/rabbitmq-supervisor-bundle#16]
Hi,

I have been trying to use this bundle on a symfony3 app that is deployed onto an elasticbeanstalk generated environment. 

I have a postdeploy script that is set to execute the rabbitmq rebuild command like so:

```
files:
  "/opt/elasticbeanstalk/hooks/appdeploy/post/101_run_supervisord.sh":
    mode: "000755"
    owner: root
    group: root
    content: |
      #!/usr/bin/env bash
      set -xe
      
      . /opt/elasticbeanstalk/support/envvars
      
      sudo -Eu webapp /var/app/current/bin/console rabbitmq-supervisor:rebuild
```

The problem that I am encountering is that the deployment hangs on the rebuild command. I discovered this because while the deployment was waiting for the command to "complete" I ssh'd to the server and ran  rabbitmq-supervisor:control stop. This allowed the deployment to be finalized.

Any ideas what could be causing this?

**Comment by Phobetor** [comment]
Hi @ssammut,

that sounds like the `rebuild` command waited for the `supervisord` process to stop but that never happend but your manual call of the `stop` command managed to stop the `supervisord` process.

Have you used the same sudo parameters to call the `stop` command? What happens when you call the `rebuild` command manually?

**Comment by ssammut** [comment]
Hi @Phobetor 

Yes I used the same sudo parameters to run stop. If I call rebuild manually everything works as expected, the commands ends and supervisord is running in the background.

I just noticed that if I start supervisord manually and after that I deploy to trigger the rebuild, a new supervisord is spawned

```
1 S webapp   23449     1  0  80   0 - 53963 -      May22 ?        00:00:07 /usr/bin/python2.7 /usr/bin/supervisord --configuration=/var/app/current/app/../bin/supervisor/staging/supervisord.conf --identifier=symfony2
1 S webapp   24319     1  0  80   0 - 53918 -      06:39 ?        00:00:00 /usr/bin/python2.7 /usr/bin/supervisord --configuration=/var/app/current/app/../bin/supervisor/staging/supervisord.conf --identifier=symfony2
```

**Comment by Phobetor** [comment]
Hi @ssammut,

the double supervisord instance looks like the `supervisord.pid` file is getting lost during deployment. I assume that you use some kind of rolling deployment that switches the symfony root directory to a new version. If your `supervisord.pid` and `supervisord.sock` files are inside of that directory, they will not exist in the new version and therefore the rebuild command will not be able to determine the process id, concludes that supervisord is not running and spawns a new instance.

To avoid that I am using a shared directory outside of the symfony root. During deployment, the contents of that directory are symlinked to the corresponding places inside of the symfony root. Inside of that directory I have a `supervisor-instance` directory:
```
web/
|-- shared
|   |-- app
|   |   |-- supervisor-instance
|-- current
|   |-- app
|   |   |-- supervisor-instance -> web/shared/app/supervisor-instance
```

The `.pid` and `.sock` (and to be complete the `.log` file, too) are configured to be created inside of that shared directory:
```yml
rabbit_mq_supervisor:
    paths:
        pid_file:                       "%kernel.root_dir%/supervisor-instance/supervisord.pid"
        sock_file:                      "%kernel.root_dir%/supervisor-instance/supervisord.sock"
        log_file:                       "%kernel.root_dir%/supervisor-instance/supervisord.log"
```

That way, these files survive the rolling deploy and the `rebuild` command is able to find and kill the correct `supervisord` instance.

If that is also the reason for your hanging rebuild command is hard to tell. It does not hang In my test case. I just got the multiple `supervisord` instances.

**Comment by ssammut** [comment]
@Phobetor I moved the pid and sock files and you suggested, which was obviously causing the spawn of more than one supervisord process.

Some further details regarding the hanging on the deployment. Doing an strace on the supervisord process gives:

```
wait4(-1, 0x7ffdf359dccc, WNOHANG, NULL) = -1 ECHILD (No child processes)
gettimeofday({1495542500, 964193}, NULL) = 0
poll([{fd=6, events=POLLIN|POLLPRI|POLLHUP}], 1, 1000) = 0 (Timeout)
wait4(-1, 0x7ffdf359dccc, WNOHANG, NULL) = -1 ECHILD (No child processes)
gettimeofday({1495542501, 965021}, NULL) = 0
```

and /proc/xxx/fd/6 is polling on a socket:

`lrwx------ 1 webapp webapp 64 May 23 12:04 6 -> socket:[494698]`

but I can;t find anything with that socket in netstat. 

I took a different approach to verify where the issue might be coming from. Instead of calling rebuild during the deploying I commited the conf files to the repository and changed the post deployment script to start the supervisord manually.

```
files:
  "/opt/elasticbeanstalk/hooks/appdeploy/post/101_run_supervisord.sh":
    mode: "000755"
    owner: root
    group: root
    content: |
      #!/usr/bin/env bash
      set -xe
      
      . /opt/elasticbeanstalk/support/envvars

      #sudo -Eu webapp /var/app/current/bin/console rabbitmq-supervisor:rebuild
      sudo -Eu webapp /usr/bin/supervisord --configuration=/var/app/current/app/../bin/supervisor/staging/supervisord.conf --identifier=symfony2
```

This does not hang the deployment.

**Comment by ssammut** [comment]
The waiting on the socket is something expected with supervisord, it was a wrong assumption to think that it might be related to the issue, my bad.

**Comment by ssammut** [comment]
Just adding more details regarding the issue just in case someone ever encounters a similar problem with AWS ElasticBeanstalk.

- So I start the deployment: `eb deploy envname`
- Then I find the pid taking care of the deployment on the server and I strace that which gives me

```
read(16, "+ sudo -Eu webapp /var/app/curre"..., 8192) = 75
read(16, 0x56442e53fbf0, 8192)          = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=14692, si_status=0, si_utime=0, si_stime=0} ---
read(16, 
```

- I look for the fd in /proc which is a pipe `lr-x------ 1 root root 64 Jul  3 12:25 16 -> pipe:[88486]`

- Listing all the child processes related to the deployment shows a <defunct> bash script

```
4 S root      9708     1  0  80   0 - 132821 poll_s 10:12 ?       00:00:14 /usr/bin/python2.7 /opt/aws/bin/cfn-hup
0 S root     13443  9708  0  80   0 - 28802 wait   12:25 ?        00:00:00  \_ /bin/bash -e /opt/elasticbeanstalk/bin/command-processor
4 S root     13444 13443  0  80   0 - 76951 pipe_w 12:25 ?        00:00:00      \_ /opt/elasticbeanstalk/lib/ruby/bin/ruby /opt/elasticbeanstalk/lib/ruby/bin/command-processor
4 Z root     14692 13444  0  80   0 -     0 -      12:26 ?        00:00:00          \_ [bash] <defunct>
```

- The command is executed by the command-processor in the following way

```sudo /opt/elasticbeanstalk/lib/ruby/bin/ruby /opt/elasticbeanstalk/lib/ruby/bin/command-processor | sudo -Eu webapp /var/app/current/bin/console rabbitmq-supervisor:rebuild```

This might be the reason why the deployment is hanging. The command-processor keeps waiting for the process to end but it is a <defunct> state.

**Comment by maedchenflohmarkt** [comment]
Hi @ssammut 

can you add the shell output of `ps xxx` where `xxx` is the id of the `supervisord` process
- while the supervisord instance is running and
- when the deployment hangs?

There is a chance that the rebuild command is just unable to determine if the supervisord instance stopped.

**Comment by Phobetor** [comment]
Hi @ssammut

can you add the shell output of ps xxx where xxx is the id of the supervisord process

while the supervisord instance is running and
when the deployment hangs?
There is a chance that the rebuild command is just unable to determine if the supervisord instance stopped.

**Comment by ssammut** [comment]
The process before the deployment:

```
  PID TTY      STAT   TIME COMMAND
17961 ?        Ss     0:00 /usr/bin/python2.7 /usr/bin/supervisord --configuration=/var/app/current/app/../bin/supervisor/staging/supervisord.conf --identifier=symfony2
```

while it calls rebuild
```
[ec2-user@ip-10-50-3-186 log]$ ps -leaf | grep super
1 S webapp   17961     1  0  80   0 - 53930 -      13:19 ?        00:00:00 /usr/bin/python2.7 /usr/bin/supervisord --configuration=/var/app/current/app/../bin/supervisor/staging/supervisord.conf --identifier=symfony2
4 S root     19455 18045  0  80   0 - 28803 -      13:22 ?        00:00:00 bash /opt/elasticbeanstalk/hooks/appdeploy/post/101_run_supervisord.sh
4 S root     19459 19455  0  80   0 - 46669 -      13:22 ?        00:00:00 sudo -Eu webapp /var/app/current/bin/console rabbitmq-supervisor:rebuild
4 R webapp   19460 19459  0  80   0 - 114119 -     13:22 ?        00:00:00 php /var/app/current/bin/console rabbitmq-supervisor:rebuild
0 S ec2-user 19462  8704  0  80   0 - 27614 pipe_w 13:22 pts/0    00:00:00 grep --color=auto super

```

deployment hangs:

```
  PID TTY      STAT   TIME COMMAND
19507 ?        Ss     0:00 /usr/bin/python2.7 /usr/bin/supervisord --configuration=/var/app/current/app/../bin/supervisor/staging/supervisord.conf --identifier=symfony2
```

**Comment by ssammut** [comment]
Finally solved. As expected elasticbeanstalk kept waiting for the process to terminate. 

`sudo -Eu webapp nohup /var/app/current/bin/console rabbitmq-supervisor:rebuild >/dev/null 2>&1 &`

Just make sure that it is running in the background and ignore all output.
