### ISSUE TITLE
Is supervisor needed ?

### ISSUE THREAD

**Issue by nikophil** [Phobetor/rabbitmq-supervisor-bundle#17]
Hello,

i tried your bundle, and that wasn't working : 
all the *.conf files were created, but the consumers were not working...

Then after some reading, i tried to install "supervisor" program via "apt-get install supervisor", and then the consumers were working, but the "rebuild" comment didn't gave me the terminal back.... moreover ctrl + c isn't working.

I got few questions, please :
- I supervisor bin really needeed ? if yes, i think you sould update the doc
- Is it a normal behavior that the rebuild command seems not finishing ?

thank you for your answer and your work.

**Comment by m0onspell** [comment]
Don't use this crap. That's what I come up with, not sure if it's best solution, but at least it works:

```sh
$ apt-get install supervisor
```

Put this into root of my project with name `supervisord.conf`
```
[supervisord]
logfile = /tmp/supervisord.log
logfile_maxbytes = 10MB
directory = %(here)s
pidfile = /tmp/supervisord.pid
[program:todo]
command = php /var/www/symfony/bin/console rabbitmq:consumer -w sync
autostart = true
autorestart = true
```
From the same place:
```sh
$ supervisord
```

**Comment by Phobetor** [comment]
Hi @nikophil,

> Is supervisor bin really needed ? if yes, i think you sould update the doc

Yes, [supervisor](http://supervisord.org/) is needed. This bundle's `rabbitmq-supervisor:rebuild` command creates all required configuration files and then simply starts supervisor with that configuration.

Thanks for the hint, I will add a check to the commands to assure that the binary is available before using it. I will also add supervisor website links to the doc to clarify that “supervisor” is an external tool and supervision comes not from this bundle.

> Is it a normal behavior that the rebuild command seems not finishing ?

No, the command should exit normally after starting the supervisor daemon. Can you give me some information about the system you are using?

**Comment by nikophil** [comment]
hello, and thanks for your answer.

- Isn't there any way to embed supervisor bin in your bundle (and the bin would be moved in the "/bin" directory of the app ?
- I'm running a symfony 2.8 app under docker :
    - nginx (from nginx official docker image)
    - php fpm5.6 (from debian jessie)
    - rabbitmq:management-alpine

if you need more information, don't hesitate...

**Comment by Phobetor** [comment]
Hi @nikophil,

> Isn't there any way to embed supervisor bin in your bundle (and the bin would be moved in the "/bin" directory of the app ?

That is far beyond the scope of a symfony bundle. `supervisor` is written in python and therefore has its own tail of dependencies. There are ready-to-use packages for all platforms. As you use alpine linux, you can simply use [this supervisor package for alpine linux](https://pkgs.alpinelinux.org/package/edge/main/x86_64/supervisor). Other ways to install supervisor can be found in the [supervisor installation guide](http://supervisord.org/installing.html).

> I'm running a symfony 2.8 app under docker :
> - rabbitmq:management-alpine

I will run some tests on alpine linux to find out if there are some pitfalls with that distribution.

**Comment by nikophil** [comment]
ok you're right...

the package i get form apt-get is not the good one for alpine ?

**Comment by Phobetor** [comment]
Hi @nikophil,

I am not used to alpine linux. As far as I can see, alpine uses a package manager command called `[apk](https://wiki.alpinelinux.org/wiki/Alpine_Linux_package_management)`. The install command for alpine linux would be:
```sh
$ apk add supervisor
```

I do not know if the packages are compatible. Personally I would not consider experimenting with that and just use the distribution's build in installation mechanism.

**Comment by Phobetor** [comment]
Hi @nikophil,

Were you able to install `supervisor` and get this running?

**Comment by nikophil** [comment]
Hello,

yes i was, thanks

2018-05-21 13:26 GMT+02:00 Phobetor <notifications@github.com>:
