### ISSUE TITLE
No errors if supervisor do not exists...

### ISSUE THREAD

**Issue by NikitaKharkov** [Phobetor/rabbitmq-supervisor-bundle#20]
I think you should add some check of supervisor. I spent about 30 minutes to find that in past I installed it in docker image by hands. And now, then I returned to this task, I try to build, to start, to init and commands doesn't help me. Only after some time I called to mind that I haven't installed supervisor yet

**Comment by Phobetor** [comment]
Sorry for the inconvenience @NikitaKharkov . You are absolutely right. I will add error output for that case.

**Comment by NikitaKharkov** [comment]
Thank you very much!

**Comment by kisztof** [comment]
#22 Here you are :)

**Comment by Phobetor** [comment]
Should be handled by #22 which is merged to master and released as new version [3.0.0](https://github.com/Phobetor/rabbitmq-supervisor-bundle/releases/tag/3.0.0).
@NikitaKharkov please tell me if that works for your case.
