### ISSUE TITLE
With test environment not correct command

### ISSUE THREAD

**Issue by NikitaKharkov** [Phobetor/rabbitmq-supervisor-bundle#23]
When I try to test my consumer I couldn't understand why I my consumers do not up. After search I found that the command in test environment is

```command=php /var/www/der-ibe/ibe-fair-api/vendor/bin/phpunit rabbitmq:consumer import --messages=250 --env=test```

In dev and prod env everything is ok.
So the phpunit it execute. :) Fix it please. Thanks.

**Comment by NikitaKharkov** [comment]
I'm sorry, I forgot to say that this bug is appeared when I run tests. And only this case

**Comment by Phobetor** [comment]
Hi @NikitaKharkov 

I changed the way the console path is determined. It should no longer use your `phpunit` executable.

You can try the current `dev-master` to check if this works for you.
