### ISSUE TITLE
Command does not exit

### ISSUE THREAD

**Issue by yourilefers** [Phobetor/rabbitmq-supervisor-bundle#29]
This may be by design, but the init commands (like start) do not exit properly when used in combination with Docker (Compose). I fixed this by migrating from the Process->run command to the Process->start command. It may be a good idea to make this an option, as "start" should just start the daemon and than exit the command. "Run" will wait for the command to exit, which gave problems running it with "docker exec".

_For reference; I used Symfony 3.x and PHP-FPM 7.1._

**Comment by tackerm** [comment]
I can confirm this issue, although in a different setup. The `Supervisor::run()` method hangs when calling `$this->getContainer()->get('phobetor_rabbitmq_supervisor')->start()` in a custom console command. Replacing `$p->run()` with `$p->start()` fixes it.

Also note that calling [`wait()` after `run()`](https://github.com/Phobetor/rabbitmq-supervisor-bundle/blob/master/Services/Supervisor.php#L63) doesn't make much sense, as `run()` already calls `wait()` internally...
