### ISSUE TITLE
Can it be used with SwarrotBundle?

### ISSUE THREAD

**Issue by zspine** [Phobetor/rabbitmq-supervisor-bundle#32]
Just wondering whether it's safe to use it with https://github.com/swarrot/SwarrotBundle or not?

**Comment by Phobetor** [comment]
Hello @zspine 

This bundle currently fetches the configuration from the values created by `php-amqplib/rabbitmq-bundle`. I didn't take a deeper look at SwarrotBundle but I assume that it uses other configuration values. Therefore it will most likely not work.

**Comment by zspine** [comment]
Hi @Phobetor,

Thank you very much for the detailed explanation. Are you using any strategy pattern to import the configuration values?

**Comment by Phobetor** [comment]
Hello @zspine 

Sorry about the delayed answer. Currently the import is hard coded because I crated this bundle to use with rabbitmq-bundle. But this can change if there are other good and widely used bundles.
