### ISSUE TITLE
How can i Implement logrorate?

### ISSUE THREAD

**Issue by varnitsaini** [Phobetor/rabbitmq-supervisor-bundle#33]
For the logs that are generated how can i log rotate, limiting the rotated files by specific amount(eg maximum 5 files) and size for each file?

**Comment by Phobetor** [comment]
Hi @varnitsaini 

in general you can use [logrotate](https://manpages.debian.org/jessie/logrotate/logrotate.8.en.html) to achieve this. This has the advantage that you don't need to change anything in your `supervisord` configuration. You just configure `logrotate` to handle the log file.

`supervisord` also [has an option](http://supervisord.org/logging.html#activity-log-rotation) to rotate the log files it creates. Maybe you can set this option in a system-wide configuration. This bundle has no configuration for this at the moment.
