### ISSUE TITLE
There are no commands defined in the "rabbitmq-supervisor" namespace

### ISSUE THREAD

**Issue by jvkiran** [Phobetor/rabbitmq-supervisor-bundle#44]
command: sudo -u www-data SYMFONY_ENV=prod php app/console rabbitmq-supervisor:build --env=prod

error: There are no commands defined in the "rabbitmq-supervisor" namespace

Also rabbitmq-server and supervisor both services are running in production server.

Need help

**Comment by jvkiran** [comment]
Hi @Phobetor 
I'm new to symfony

I'm using Symfony 3.4.9 (kernel: app, env: prod, debug: false).

I simply ran below commands:
 "sudo apt install -y rabbitmq-server" & sudo apt-get install -y supervisor and then composer install

i'm using this repo [superdesk](https://github.com/superdesk/web-publisher)

**Comment by Phobetor** [comment]
Hi @jvkiran 

In that case please follow the installation section that you can find in this bundle's [readme](https://github.com/Phobetor/rabbitmq-supervisor-bundle). There you can find information how you can install this bundle via `composer require` and then add the mentioned line to your `AppKernel.php`.

**Comment by jvkiran** [comment]
Hi @Phobetor,

I followed installation section, following error appeared.

cmd: sudo -u www-data SYMFONY_ENV=prod php app/console rabbitmq-supervisor:rebuild --env=prod

13:35:39 ERROR     [console] Error thrown while running command "rabbitmq-supervisor:rebuild --env=prod". Message: "You have requested a non-existent service "phobetor_rabbitmq_supervisor"." ["exception" => Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException { …},"command" => "rabbitmq-supervisor:rebuild --env=prod","message" => "You have requested a non-existent service "phobetor_rabbitmq_supervisor"."] []

In Container.php line 348:
                                                                             
  You have requested a non-existent service "phobetor_rabbitmq_supervisor".

**Comment by jvkiran** [comment]
Thanks

**Comment by jvkiran** [comment]
I've solved the problem, Thanks

**Comment by eugeneonos** [comment]
It would help others if you can please tell us how you solved the problem.Thanks
