### ISSUE TITLE
startretries option

### ISSUE THREAD

**Issue by markitosgv** [Phobetor/rabbitmq-supervisor-bundle#49]
is it possible to add startretries option to supervisor/consumer configuration?

**Comment by 6ecuk** [comment]
I think need add more options not just startretries. I wrote before about missing parameters in issue https://github.com/Phobetor/rabbitmq-supervisor-bundle/issues/26
I will try create pull request with new options

**Comment by Phobetor** [comment]
@markitosgv
If you update to [version 3.2.0](https://github.com/Phobetor/rabbitmq-supervisor-bundle/releases/tag/3.2.0) you can set the worker's `startretries` configuration.
