### ISSUE TITLE
Symfony3 support

### ISSUE THREAD

**Issue by trousers** [Phobetor/rabbitmq-supervisor-bundle#5]
Are there any plans to add symfony3 support?

**Comment by Phobetor** [comment]
Of course. Most of the bundle should be already compatible. I am currently testing it and will commit and release a new version within a few days.

**Comment by tiborb** [comment]
+1

**Comment by Phobetor** [comment]
Version 1.5.0 is compatible with symfony version 3.

**Comment by trousers** [comment]
nice one
