### ISSUE TITLE
How can I ignore some queue?

### ISSUE THREAD

**Issue by Sermanes** [Phobetor/rabbitmq-supervisor-bundle#59]
Hi! When I execute `rebuild` command, it generated all workers from all the queues I have in my project. But I want to ignore some queues because of different reassons.

How can I do it?

**Comment by Phobetor** [comment]
@Sermanes 
If you update to version [3.2.0](https://github.com/Phobetor/rabbitmq-supervisor-bundle/releases/tag/3.2.0) you can set the worker's `count` configuration to `0` to not have no consumers listening to that queue.
