### ISSUE TITLE
supervisor files

### ISSUE THREAD

**Issue by trousers** [Phobetor/rabbitmq-supervisor-bundle#6]
How do I get these files? All the other files are there. 

    ├── supervisord.log
    ├── supervisor.pid
    ├── supervisor.sock

**Comment by Phobetor** [comment]
These files (log file, unix socket and process id file) are created by supervisord on startup.

If all the configuration files exist and these file are missing it seems like supervisord is not able to start.

Is the process able to write to the missing files?

**Comment by trousers** [comment]
$ sudo service supervisord status
supervisord (pid  12795) is running...

It's running, am I supposed to point supervisord to the app/supervisor directory?

**Comment by trousers** [comment]
Ah ok..

http://supervisord.org/configuration.html

Working now, thanks!

**Comment by Phobetor** [comment]
Great to hear that, @trousers . As you figured out for yourself you need to specify the path to your configuration file if you start supervisord directly. Alternatively you can use the symfony console:
```sh
$ console rabbitmq-supervisor:control start
```
This will build the supervisord command with all the needed parameters for you.

**Comment by trousers** [comment]
Actually it didn't. When I start through the symfony console the 3 files do not generate in the directory.

When I do
$ supervisord -c /path/to/app/superisor/supervisord.conf
$ sudo service supervisord start

I get the pid and log but no sock.

So it's not working :/  I think I should read the supervisor manual....
